###DATA Endpoint
GET http://localhost:8000/dashboard


###DATA Endpoint for dashboard
GET http://localhost:8000/

###DATA Endpoint for api data
GET http://localhost:8000/api/data


###DATA Endpoint to create user
POST http://localhost:8000/api/createUser
Content-Type: application/json

{
  "name": "Edward"
}

###Delete user endpoint
DELETE http://localhost:8000/api/deleteUser
